// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconArrow: typeof import('./src/components/icons/IconArrow.vue')['default']
    IconBookmark: typeof import('./src/components/icons/IconBookmark.vue')['default']
    IconClose: typeof import('./src/components/icons/IconClose.vue')['default']
    IconDelete: typeof import('./src/components/icons/IconDelete.vue')['default']
    IconDrag: typeof import('./src/components/icons/IconDrag.vue')['default']
    IconEdit: typeof import('./src/components/icons/IconEdit.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
  }
}
